package com.walls.entidades;
// Generated 25-oct-2020 17:32:58 by Hibernate Tools 5.4.14.Final

import java.util.Calendar;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.hibernate.annotations.GenericGenerator;

/**
 * Cita generated by hbm2java
 */
public class Cita implements java.io.Serializable {

	private int codCita;
	private Integer codCliente;
	private Integer codMascota;
	private Date fecha;
	private String hora;
	private String tipoCita;
	private String observacion;

	public Cita() {
	}

	public Cita(int codCita) {
		this.codCita = codCita;
	}

	public Cita( Integer codCliente, Integer codMascota, Date fecha, String hora, String tipoCita, String observacion) {
		this.codCita = codCita;
		this.codCliente = codCliente;
		this.codMascota = codMascota;
		this.fecha = fecha;
		this.hora = hora;
		this.tipoCita = tipoCita;
		this.observacion = observacion;
	}
	
	

	public String getHora() {
		return hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

//	@Id
//	@GenericGenerator(name="kaugen" , strategy="increment")
//	@GeneratedValue(generator="kaugen")
//	@Column(name="cod_cita") 
	public int getCodCita() {
		return this.codCita;
	}

	public void setCodCita(int codCita) {
		this.codCita = codCita;
	}

	public Integer getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	public Integer getCodMascota() {
		return this.codMascota;
	}

	public void setCodMascota(Integer codMascota) {
		this.codMascota = codMascota;
	}

	public Date getFecha() {
		return this.fecha;
	}
	
	public String getFechaToString() {
		
		Calendar cal = Calendar.getInstance();
		cal.setTime(fecha);
		
		String dia = Integer.toString(cal.get(Calendar.DATE));
		String mes = Integer.toString(cal.get(Calendar.MONTH)+1);
		String annio = Integer.toString(cal.get(Calendar.YEAR));
		
		return dia + "/"+mes + "/" + annio;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTipoCita() {
		return this.tipoCita;
	}

	public void setTipoCita(String tipoCita) {
		this.tipoCita = tipoCita;
	}

	public String getObservacion() {
		
		if(observacion.equals(""))
			return "SIN OBSERVACIONES";
		else
			return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
