package com.walls.entidades;
// Generated 25-oct-2020 17:32:58 by Hibernate Tools 5.4.14.Final

import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int codCliente;
	private String dni;
	private String nombre;
	private String pass;
	private String mail;
	private Date fechaNac;
	private String direccion;
	private String localidad;

	public Cliente() {
	}

	public Cliente(int codCliente) {
		this.codCliente = codCliente;
	}

	public Cliente(int codCliente, String dni, String nombre, String pass, String mail, Date fechaNac, String direccion,
			String localidad) {
		this.codCliente = codCliente;
		this.dni = dni;
		this.nombre = nombre;
		this.pass = pass;
		this.mail = mail;
		this.fechaNac = fechaNac;
		this.direccion = direccion;
		this.localidad = localidad;
	}

	public int getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(int codCliente) {
		this.codCliente = codCliente;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getDireccion() {
		if(this.direccion != null)
			return this.direccion;
		else
			return "-- no especificado --";
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLocalidad() {
		if(this.localidad != null)
			return this.localidad;
		else
			return "-- no especificado --";
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

}
